---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled


jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels and Add Comment
        id: check_labels_and_comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get PR info: id and labels
            const prNumber = context.payload.pull_request.number;
            const labels = context.payload.pull_request.labels.map(label => label.name);

            // Array of labels to check for
            const validLabels = ['enhancement', 'deprecated', 'refactoring', 'pr: breaking', 'pr: clean', 'pr: fix', 'pr: new feature', 'pr: test'];

            // If no descriptive label is set, add a comment in the PR and make the action check fail
            if (!validLabels.every(label => labels.includes(label))) {
              const comment = ':warning: :warning: :warning:<br>@'+context.repo.owner+' your PR does not include any descriptive label :label:<br> Make sure to add an appropriate [PR label](https://github.com/sofa-framework/sofa/labels) before merge.<br>:warning: :warning: :warning:';
              github.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
              core.setFailed('Invalid PR label')
            }

            // Add all PR labels in log
            console.log('Labels:', labels.join(', '));
