name: CMake/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install_deps:
    runs-on: ubuntu-latest
    steps:
      - name: build-tools
        run: apt install build-essential ninja-build clang
      - name: project-tools
        run: apt install cmake ccache
      - name: qt5-deps
        run: apt install qt5-default
      - name: boost-deps
        run: apt install libboost-atomic-dev libboost-chrono-dev \
             libboost-date-time-dev libboost-filesystem-dev \
             libboost-locale-dev libboost-regex-dev libboost-system-dev \
             libboost-thread-dev libboost-program-options-dev
      - name: python2-deps
        run: apt install python2.7-dev python-numpy python-scipy
      - name: extra-deps
        run: apt install libpng-dev libjpeg-dev libtiff-dev zlib1g-dev libglew-dev
        
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create_dir
      run: mkdir build
    - name: cmake
      run: cmake -G Ninja -DCMAKE_CXX_COMPILER="/usr/bin/clang++" \
           -S . -B ./build \
           -DSOFA_BUILD_METIS=ON -DPLUGIN_SOFASPARSESOLVER=ON
    - name: make
      run: make -j4
    - name: make install
      run: make install -j4

  # run-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: run-tests
  #     run: sh build/bin/run-tests.sh
