name: CMake/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: bmarques68/sofa-ubuntu:18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://bmarques68/sofa-ubuntu:18.04          
      - name: configure
        run:
          mkdir -p build;
          cd build;
          cmake .. -G Ninja -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DSOFA_BUILD_METIS=ON -DPLUGIN_SOFASPARSESOLVER=ON
          
      - uses: docker://bmarques68/sofa-ubuntu:18.04          
      - name: build
        run:
          cd build;
          ninja;
          ninja install

  # run-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: run-tests
  #     run: sh build/bin/run-tests.sh
