name: Post - Announcement GHD topics

on:
  discussion:
    types: [created]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        if: ( github.context.payload.discussion.category.name == 'Announcement' ) || ( github.context.payload.discussion.category.name == 'Share your achievements' )
        run: |
          pip install python-graphql-client
          pip install python-dateutil
          pip install requests
        working-directory: ${{ github.workspace }}

      - name: Run script post-discord-message.py
        if: ( github.context.payload.discussion.category.name == 'Announcement' ) || ( github.context.payload.discussion.category.name == 'Share your achievements' )
        run: |
          python scripts/discord/post-discord-message.py
        working-directory: ${{ github.workspace }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_ANNOUNCEMENTS_WEBHOOK_URL }}
          MESSAGE: ":loudspeaker: New post \"${{github.context.payload.discussion.category.name}}\" :arrow_right: **[${{github.context.payload.discussion.title}}](https://github.com/sofa-framework/sofa/discussions/${{github.context.payload.discussion.number}})** by [${{github.context.payload.discussion.author.login}}](https://github.com/${{github.context.payload.discussion.author.login}})"
          BOT_NAME: "Discussion announcement"
          EMBEDS_TITLE: ${{github.context.payload.discussion.title}}
          EMBEDS_URL: "https://github.com/sofa-framework/sofa/discussions/${{github.context.payload.discussion.number}}"

