name: Post - Github activity (PRs, issues, stars)

on:
  watch:
    types: [started]
  issues:
    types: [opened]
  pull_request:
    types: [opened,review_requested,closed]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install python-graphql-client
          pip install python-dateutil
          pip install requests
        working-directory: ${{ github.workspace }}

      # PR opened
      - name: Run script post-discord-message.py for PR opened (main)
        if: (github.event_name == 'pull_request') && (github.pull_request.action == 'opened')
        run: |
          python scripts/discord/post-discord-message.py
        working-directory: ${{ github.workspace }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_MAIN_WEBHOOK_URL }}
          MESSAGE: ":new: PR opened:"
          BOT_NAME: "SOFA Github bot"
          EMBEDS_TITLE: "#${{context.payload.pull_request.number}} ${{context.payload.pull_request.title}}"
          EMBEDS_URL: "https://github.com/sofa-framework/sofa/pull/${{context.payload.pull_request.number}}"
          EMBEDS_DESCRIPTION: "Authored by @${{context.payload.pull_request.author.login}}\nLabels: ${{context.payload.pull_request.labels.name}}"

      # PR merged
      - name: Run script post-discord-message.py for PR merged
        if: (github.event_name == 'pull_request') && (github.pull_request.action == 'closed') && (github.event.pull_request.merged == true)
        run: |
          python scripts/discord/post-discord-message.py
        working-directory: ${{ github.workspace }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_MAIN_WEBHOOK_URL }}
          MESSAGE: ":raised_hands: Thanks @${{context.payload.pull_request.merged_by.login}} for merging PR [#${{context.payload.pull_request.number}}](https://github.com/sofa-framework/sofa/pull/${{context.payload.pull_request.number}}) ${{context.payload.pull_request.title}} (author: @${{context.payload.pull_request.author.login}})"
          BOT_NAME: "SOFA Github bot"
          EMBEDS_TITLE: ""
          EMBEDS_URL: ""
          EMBEDS_DESCRIPTION: ""

      # PR review requested event
      - name: Run script post-discord-message.py for PR review request
        if: (github.event_name == 'pull_request') && (github.pull_request.action == 'review_requested')
        run: |
          python scripts/discord/post-discord-message.py
        working-directory: ${{ github.workspace }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_MAIN_WEBHOOK_URL }}
          MESSAGE: ""
          BOT_NAME: "SOFA Github bot"
          EMBEDS_TITLE: ""
          EMBEDS_URL: ""
          EMBEDS_DESCRIPTION: ":eyeglasses: Review requested: ${{context.payload.pull_request.requested_reviewers}} would you please review [#${{context.payload.pull_request.number}}](https://github.com/sofa-framework/sofa/pull/${{context.payload.pull_request.number}})?"

      # Issue related event
      - name: Run script post-discord-message.py for Issue opened
        if: github.event_name == 'issues'
        run: |
          python scripts/discord/post-discord-message.py
        working-directory: ${{ github.workspace }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_MAIN_WEBHOOK_URL }}
          MESSAGE: ":space_invader: New issue raised"
          BOT_NAME: "SOFA Github bot"
          EMBEDS_TITLE: "\"${{context.payload.issue.title}}\" by @${{context.payload.issue.user.login}}"
          EMBEDS_URL: "https://github.com/sofa-framework/sofa/issues/${{context.payload.issue.number}}"
          EMBEDS_DESCRIPTION: ""

      # Star/watch related event
      - name: Run script post-discord-message.py for stars
        if: github.event_name == 'watch'
        run: |
          python scripts/discord/post-discord-message.py
        working-directory: ${{ github.workspace }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_MAIN_WEBHOOK_URL }}
          MESSAGE: ":fire: :fire: Come ON! :fire: :fire: \nOne new :star: for SOFA on Github"
          BOT_NAME: "SOFA Github bot"
          EMBEDS_TITLE: ""
          EMBEDS_URL: ""
          EMBEDS_DESCRIPTION: ""

